# Generated by Django 6.0.4 on 2026-04-28 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('janr', models.CharField(choices=[('badiiy', 'Badiiy'), ('Selfhelp', 'Self Help')], default='boshqa', max_length=20)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('mavjud', models.BooleanField(default=True)),
                ('yaratildi', models.DateTimeField(auto_now_add=True)),
                ('ega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
