# Generated by Django 6.0.4 on 2026-05-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almashitirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('qabul', 'Qabul qilindi'), ('rad', 'Rad etildi')], default='kutilmoqda', max_length=20)),
                ('yaratildi', models.DateTimeField(auto_now_add=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorovlar', to='books.kitob')),
                ('yuboruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuborilgan_sorovlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
