# Generated by Django 6.0.4 on 2026-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_almashitirish'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='hudud',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('buxoro', 'Buxoro'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', "Qoraqalpog'iston")], default='nomalum', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(choices=[('badiiy', 'Badiiy'), ('Selfhelp', 'Self Help'), ('it', 'IT'), ('romantik', 'Romantik'), ('ilmiy_ommabop', 'Ilmiy-Ommabop'), ('biznes_iqtisod', 'Biznes-Iqtisod'), ('psixologiya', 'Psixologiya')], default='boshqa', max_length=20),
        ),
    ]
