# Generated by Django 6.0.4 on 2026-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_kitob_hudud_alter_kitob_janr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='hudud',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('samarkand', 'Samarqand'), ('buxoro', 'Buxoro'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', "Qoraqalpog'iston")], default='nomalum', max_length=20),
        ),
    ]
