# Generated by Django 6.0.4 on 2026-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_istak_taklif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='nomi',
            field=models.CharField(max_length=100),
        ),
    ]
