# Generated by Django 6.0.4 on 2026-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tasdiqlashkodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasdiqlashkodi',
            name='kod',
            field=models.CharField(max_length=6),
        ),
    ]
