# Generated by Django 6.0.4 on 2026-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tasdiqlashkodi_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasdiqlashkodi',
            name='urinishlar_soni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
